<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vak_Terkep</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Shared\Start\**" />
    <Content Remove="Views\Shared\Start\**" />
    <EmbeddedResource Remove="Views\Shared\Start\**" />
    <None Remove="Views\Shared\Start\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\sampleImages\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
